### PR TITLE
Update Server.java

### PR DESCRIPTION
**Pull request by RandomAltThing**
Updated. This can be fully implemented later and I will do it.

### CODE REVIEW

**Comment by PEMapModder** [comment]
Syntax error. Use an IDE please.

**Comment by RandomAltThing** [comment]
@PEMapModder ah. Where? I cannot use Eclipse because I have not got a clue on how to set it up :(

**Comment by RandomAltThing** [comment]
@PEMapModder I am Enderbrine101, by the way.

**Comment by PhilipShilling** [comment]
You can click on the failure icon to see the error list.

**Comment by PhilipShilling** [comment]
Also, you can use YouTube to learn how to set up Eclipse

**Comment by jython234** [comment]
http://lmgtfy.com/?q=eclipse+tutorial

**Comment by RandomAltThing** [comment]
Thanks

**Pull request closed without merging**
