### PR TITLE
Added more packets and correct mcpe version

### PR DESCRIPTION
**Pull request by RandomAltThing**
No commit message

### CODE REVIEW

**Comment by jython234** [comment]
The RedstoneLamp project is NOT a port of PocketMine! This issue has been discussed on IRC already.

**Comment by RandomAltThing** [comment]
@jython234 Stuff like SetDifficultyPacket and SetHealthPacket is the same as pocketmine but in java

**Comment by RandomAltThing** [comment]
So either remove those files or don't complain about this Pull request.

**Comment by jython234** [comment]
@RandomAltThing Of course they are similar to PocketMine, because you can't
change the structure of a packet or else it won't work xD. Anyway, you'll
have to wait for @PhilipShilling to decide to merge this PR.

On Saturday, August 15, 2015, RandomAltThing <notifications@github.com>
wrote:

> So either remove those files or don't complain about this Pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/pull/91#issuecomment-131402852>
> .
>


--

**Comment by RandomAltThing** [comment]
@Jython234 Alright. Can you please get PEMapModder to stop being so annoying on IRC

**Pull request closed without merging**
