### PR TITLE
Lang updates

### PR DESCRIPTION
**Pull request by MCPEGamerJPatGitHub**

### CODE REVIEW

**Comment by RandomAltThingy** [comment]
Actually, this should be <code>en_US.lang</code>. US and UK are basically the same but that's how its done in many projects.

**Comment by RandomAltThingy** [comment]
It could have a dash (<code>-</code>) but its normally underscore. Like I said, it doesn't have to be.

**Comment by RandomAltThingy** [comment]
You do know .lang files don't use # for a comment, right? :P

**Comment by RandomAltThingy** [comment]
Nevermind you can use #. Feel free to use the English (French is a bit incorrect..) stuff from my PR. Just give me slight credit.

https://github.com/RedstoneLamp/RedstoneLamp/pull/112/files

**Comment by MCPEGamerJPatGitHub** [comment]
It doesn't matter even if I use # because I haven't actually added the stuff in yet

**Comment by PEMapModder** [comment]
@RandomAltThingy we haven't actually implemented languages yet, so there actually isn't a standard.

**Comment by MCPEGamerJPatGitHub** [comment]
@pemapmodder We can't implement languages yet anyways

**Comment by PEMapModder** [comment]
Why not?

**Comment by MCPEGamerJPatGitHub** [comment]
Because the API is unfinished, no point doing the Lang til it's almost done

**Comment by PEMapModder** [comment]
Yes. Therefore, it is pointless to create an empty file saying `#To be worked on`. Considering that this pull request contains invalid content, I am closing this.

**Comment by MCPEGamerJPatGitHub** [comment]
@pemapmodder You haven't seen the other one...

**Comment by PEMapModder** [comment]
For further discussion, please go on the IRC channel or Gitter.

**Comment by RandomAltThingy** [comment]
@PEMapModder That's why my PR included some lang

**Comment by PEMapModder** [comment]
Please move discussion to [Gitter](//gitter.im/RedstoneLamp/RedstoneLamp).

**Pull request closed without merging**
