### PR TITLE
Created this for future purposes

### PR DESCRIPTION
**Pull request by EnderBrine101**

### CODE REVIEW

**Comment by EnderBrine101** [comment]
@PEMapModder Dont say this is irrelivent - its for future purposes. Its based on the file from bukkit, but not exactly.

**Comment by PhilipShilling** [comment]
Achievements are entirely server-side... The MCPE client does not currently have achievements.  For that reason, this file would be useless.

**Comment by EnderBrine101** [comment]
Actually pocketmine has achivements.

**Comment by PhilipShilling** [comment]
@EnderBrine101 Again, server-side

**Comment by EnderBrine101** [comment]
Oh well, it adds more of a PC feel. Obviously it would be a last priority but still.

**Comment by PEMapModder** [comment]
@EnderBrine101 if you create PRs that add nothing to the result but create more TODOs, you are basically requesting not contributing.

**Pull request closed without merging**
