### PR TITLE
Update and rename Player.java to PlayerEntity.java

### PR DESCRIPTION
**Pull request by EnderBrine101**

### CODE REVIEW

**Comment by PEMapModder** [comment]
Player and PlayerEntity are two entirely different things...

**Comment by EnderBrine101** [comment]
It was posted in the Entity folder and we already have a Player.java not in any folder. We cant have 2 player.java's, can we?

**Comment by PEMapModder** [comment]
Player.java is about the player that holds the connection, and PlayerEntity is about the entity that represents the player's spawning on the server. They are entirely two different things.

**Comment by EnderBrine101** [comment]
In the Player.java isnide the Entity folder is has the stuff like

<b>public void isSprinting</b> etc.

**Pull request closed without merging**
