### PR TITLE
Partialy Implemented Items Based On a previous pull request

### PR DESCRIPTION
**Pull request by EnderBrine101**

### CODE REVIEW

**Comment by PhilipShilling** [comment]
Youll get a TON of errors with that code.

**Comment by PEMapModder** [comment]
Please, learn Java, and use a proper IDE, and test before submitting. You don't even know what you're doing.

**Comment by EnderBrine101** [comment]
Like I said this was based on a previous pull request. The one the contained const. I realised alot of the errors thats what I get for using a slow computer.

**Comment by PEMapModder** [comment]
Read my comment. Don't submit unless the PR has no errors.

**Pull request closed without merging**
