### PR TITLE
Added a few more options. Change as you wish.

### PR DESCRIPTION
**Pull request by EnderBrine101**

### CODE REVIEW

**Comment by EnderBrine101** [comment]
Install location is where the server files will go, memory limit is too limit the amount of memory the server is allowed to use, and language is not yet implemented but will have to be due to 0.11.0 getting new languages.

**Comment by PEMapModder** [comment]
Add the options and don't implement them. This is equivalent to requesting these features.

**Comment by EnderBrine101** [comment]
I can add lang files for other languages.

**Comment by EnderBrine101** [comment]
I can add lang files for other languages.

**Comment by PhilipShilling** [comment]
That type of config will not be used as of 1.1.0

**Pull request closed without merging**
