### PR TITLE
Create TextFormat.java

### PR DESCRIPTION
**Pull request by hoyinm**

### CODE REVIEW

**Comment by hoyinm** [comment]
Haha I just completely copy from PocketMine's.  And they are just temporary.
Besides, its not your businese.

**Comment by PEMapModder** [comment]
No. The problem is, there is `const` in Java?

**Comment by PEMapModder** [comment]
According to Wikipedia:

> Interestingly, the Java language specification regards const as a reserved keyword — i.e., one that cannot be used as variable identifier — but assigns no semantics to it. It is thought that the reservation of the keyword occurred to allow for an extension of the Java language to include C++-style const methods and pointer to const type. The enhancement request ticket in the Java Community Process for implementing const correctness in Java was closed in 2005, implying that const correctness will probably never find its way into the official Java specification.

And I hope you realize saying "none of your business" to someone who wants to help is very impolite.

**Comment by EnderBrine101** [comment]
@PEMapModder Would this code work if the [code]const[/code]wasnt there? Or if you made it public enum ?

**Comment by EnderBrine101** [comment]
They really should add [code] tags on GitHub

**Comment by PEMapModder** [comment]
@EnderBrine101 https://guides.github.com/features/mastering-markdown/ that's exactly above the comment box. GitHub is not a forum. GitHub issues use GFM, not bbcode.

**Pull request merged**
