### PR TITLE
Implemented CustomPacket

### PR DESCRIPTION
**Pull request by jython234**
Changes:
- Implemented CustomPackets at CustomPacket.java
- Implemented EncapsulatedPackets at CustomPacket.java
- Made some changes to PacketHandler.java to allow CustomPacket decoding.

Things to do:
- Figure out some sort of session handling
- In that session, handle sequence numbers and message indexes.
- Respond with ACK's/NACK's accordingly.
- Handle ACK's/NACK's

### CODE REVIEW

**Comment by jython234** [comment]
BTW: The reason why the build failed is because there are some bugs. Will push a few commits to fix them.

**Comment by PEMapModder** [comment]
@jython234 if you have time, why not work on chunk sending in BlockServer? :cry:

**Comment by jython234** [comment]
@PEMapModder I've done all I could, it's just too much. I think I'll start
another repo there called BlockServer-Soft: a simple version of BlockServer
with no api. It will support 0.11.0. Maybe there I can figure out what's
wrong, and then fix the main repo. But with track and school, I don't have
much free time.

On Tuesday, May 5, 2015, PEMapModder <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> if you have time, why not work
> on chunk sending in BlockServer? [image: :cry:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/pull/41#issuecomment-98986841>
> .
>


--

**Comment by jython234** [comment]
I also just wanted to help out this project, their forums has a nice theme :+1:.

**Pull request merged**
