### PR TITLE
Added new packets ans updated some to 0.12

### PR DESCRIPTION
**Pull request by RandomAltThing**

### CODE REVIEW

**Comment by jython234** [comment]
@RandomAltThing Please don't do those weird tab things PocketMine does, an example is in AnimatePacket where one of the fields has an extra tab. Other than that, good job :)

**Comment by RandomAltThing** [comment]
@jython234 Thanks ;). Sorry for some of the formatting, when pushing to github it sometimes messes it up :P

**Comment by jython234** [comment]
@RandomAltThing That's fine, I'll fix it sometime this afternoon (it's 10:18 AM here).

**Comment by PEMapModder** [comment]
@jython234 IRC please.

**Pull request merged**
