### PR TITLE
Implement some more blocks.

### PR DESCRIPTION
**Pull request by CavinMiana**
I just Implented more blocks. As you can see, there were only 4-8 blocks I think. I added 20 more I think

### CODE REVIEW

**Comment by PEMapModder** [comment]
Please combine your commits into one.

**Comment by jython234** [comment]
The Travis build is failing, please fix the errors.

**Comment by CavinMiana** [comment]
Aight

**Comment by M10360** [comment]
Haven't most if not all of these blocks been added now via #143? Can we close this?

**Comment by jython234** [comment]
Yeah most have been added, ill review more when I get home.

**Comment by jython234** [comment]
Most blocks have been added in #143, closing.

**Pull request closed without merging**
