### PR TITLE
Added server.properties

### PR DESCRIPTION
**Pull request by EnderBrine101**
It may seem pointless to have ALL this stuff, but if we get some more contributors I can see it happening within a couple of weeks! :) Feel free if you merge this to change its location. Also,  you install the server files (When we have it setup a bit better) it willwill need to check if the file is created and if not create it.

### CODE REVIEW

**Comment by EnderBrine101** [comment]
@Philip Shilling I have posted 3 pull requests already! Speed up XD

**Comment by EnderBrine101** [comment]
@RedstoneLamp I missed a few. If you merge it, I will fork it again and add a ton more i forgot

**Comment by EnderBrine101** [comment]
EDIT: Added more

**Comment by PEMapModder** [comment]
If you create useless pull requests like this, you are slowering not helping.

Edit: maybe I rather wish to see this kind of PRs in BlockServer so that it doesn't get dead :stuck_out_tongue_winking_eye:

**Comment by EnderBrine101** [comment]
@PEMapModder Probably because there hasent been a commit in 5 days :P. This sounds like its gonna be better than pocketmine and Blockserver (no offence). For a start you were talking about PocketBukkit before - so I hopped onto the github page and no commits for 2 months. Its either finished (most likely not) or dead.

**Comment by EnderBrine101** [comment]
@PEMapModder Could you make a commit? I showed philip a thing I made for /kill (dorsnt actually kill you; im waiting on the kill code being implemented) but I can publish it on a phone as the files too long. Also We already have some of the config file done - and I have chatcolors.java ready to go.

**Comment by EnderBrine101** [comment]
Cant publish*

**Comment by PEMapModder** [comment]
@EnderBrine101 when you write Java code, please use an IDE like Eclipse and make sure it doesn't have syntax or compile errors.

**Comment by EnderBrine101** [comment]
@PEMapModder Is there any for android? Its kinda hard to use a PC IDE when you dont have access to your PC right now.

**Comment by PEMapModder** [comment]
Then wait till you have access to your PC. Nobody can finish a big project on a mobile.

**Comment by EnderBrine101** [comment]
@PEMapModder Just to say it would be better to merge this now because then someone could make a way to check the option answer. E.G. Some code that could check if whitelist = true. Then we could use the code for making other thinhs like achievements.

**Comment by EnderBrine101** [comment]
@PEMapModder Why dont you contibute?

**Comment by PEMapModder** [comment]
Because I don't know what I need to help with at all. And if I had done I'd work on BlockServer instead.

**Pull request closed without merging**
