### PR TITLE
customizable Join/Quit messages

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by PEMapModder** [comment]
We are rewriting the whole code on the `rewrite` branch. We haven't added an API there yet though.

**Comment by Creeperface01** [comment]
Why do you rewrite?

**Comment by PEMapModder** [comment]
Because the structure was bad. The design was too PocketMine-like, and we have got a better design the PocketMine one.

**Comment by Creeperface01** [comment]
It is right. Redstonelamp.net too xD

**Pull request closed without merging**
