### PR TITLE
Rewrite Discussion (DO NOT MERGE!)

### PR DESCRIPTION
**Pull request by jython234**
#### DO NOT MERGE UNTIL READY.

# TODO
- [ ] Working Server

	- [ ] Pocket Edition
	
		- [x] Server List Ping/Pong
		- [ ] Player Spawning
		- [ ] Chunk Sending
		- [ ] Level Generation
		- [ ] Blocks
		- [ ] Items
		- [ ] Item Drops
		- [ ] Physics
- [ ] Plugins

	- [ ] Plugin Loading
	
		- [x] JAR File Loading
		- [ ] JavaScript File Loading
	- [ ] Plugin API
	
		- [x] PluginBase API
		- [x] Server API
		- [x] Player API
		- [ ] Item/Block API

### CODE REVIEW

**Comment by Obvisity** [comment]
Does the requests I make on previous one get automatically merged when this is finally pushed? New to coding. I'm good at small stuff and management lol

**Comment by PhilipShilling** [comment]
@Obvisity If the commit is merged to the new branch, it will be put into the master branch when we merge new into master

**Comment by jython234** [comment]
I think that the rewrite is ready to merge and overwrite the master branch. We have accomplished many things behind the scenes, but there is still much more work to do. Any opinions?

**Comment by PhilipShilling** [comment]
There are just a couple things that need to be completed beforehand like basic Plugin loading.

**Comment by jython234** [comment]
Got it.

On Friday, July 17, 2015, Philip Shilling <notifications@github.com> wrote:

> There are just a couple things that need to be completed beforehand like
> basic Plugin loading.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/pull/76#issuecomment-122435243>
> .
>


--

**Comment by jython234** [comment]
Ready for merge?

**Comment by PhilipShilling** [comment]
Yeah I think its ready

**Pull request merged**
