### PR TITLE
Added a /version command (Now Should Work)

### PR DESCRIPTION
**Pull request by EnderBrine101**

### CODE REVIEW

**Comment by PhilipShilling** [comment]
Please read the CONTRIBUTING.md before ooening pull requests. I will leave this open for another time.

**Comment by EnderBrine101** [comment]
Alright sorry.

**Comment by EnderBrine101** [comment]
@PhilipShilling I created another pull request before reading.this. sorry.

**Comment by PEMapModder** [comment]
1. You don't even know how to write strings in Java.
1. PRs with TODOs are basically feature requests.

**Comment by EnderBrine101** [comment]
Philip Shilling said the code was fine. I PMed him on the forums and he said there was an error parsing the package. I did fix that, however. Even the IDE I used said  it had no errors

**Comment by PEMapModder** [comment]
Are you sure?
https://travis-ci.org/RedstoneLamp/RedstoneLamp/jobs/60016617#L108

**Comment by PhilipShilling** [comment]
I didn't say the code was 100% correct I said I didn't see any errors.

**Pull request closed without merging**
