### PR TITLE
Fix getCommandManager() and getScriptManager()

### PR DESCRIPTION
**Pull request by RandomAltThingy**

### CODE REVIEW

**Comment by PEMapModder** [comment]
There are already lombok `@Getter` annotations for them.

**Comment by RandomAltThingy** [comment]
@PEMapModder Look in ExamplePlugin @PhilipShilling uses these methods (And obviously it gives errors) so I added this.

**Comment by RandomAltThingy** [comment]
And
```
this.getServer().commandManager() 
```
Doesn't work I have to do
```
private ConmandManager cmd;

this.cmd.registerCommand()
```
Directly.

**Comment by PEMapModder** [comment]
They work. Lombok automatically creates the getters.

**Comment by RandomAltThingy** [comment]
I'm.telling you, it doesn't work. And update ExamplePlugin then to actually work.

**Comment by PEMapModder** [comment]
This works. They may not compile correctly, but everything that should be done has been done, otherwise maven couldn't compile.

**Pull request closed without merging**
